project:
  type: website

website:
  title: "Georgia CCDR"
  repo-url: https://github.com/rvconsulting/geo-ccdr24/
  issue-url: https://github.com/rvconsulting/geo-ccdr24/issues
  repo-actions: [edit, issue]
  repo-branch: master
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: source

