project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Georgia CCDR"
  repo-url: https://github.com/rvconsulting/geo-ccdr24/
  issue-url: https://github.com/rvconsulting/geo-ccdr24/issues
  repo-actions: [edit, issue]
  repo-branch: master
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Supporting materials"
        contents: supporting-materials/*

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: source

